# Generated by Django 5.0.2 on 2024-12-05 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='productImage')),
                ('img2', models.ImageField(upload_to='productImage')),
                ('img3', models.ImageField(upload_to='productImage')),
                ('img4', models.ImageField(upload_to='productImage')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagelist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imgList', to='core.imagelist')),
            ],
        ),
    ]
