# Generated by Django 5.0.2 on 2025-01-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_category_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discountedPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rateing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='img1',
            field=models.ImageField(null=True, upload_to='productImage'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='img2',
            field=models.ImageField(null=True, upload_to='productImage'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='img3',
            field=models.ImageField(null=True, upload_to='productImage'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='img4',
            field=models.ImageField(null=True, upload_to='productImage'),
        ),
    ]
