# Generated by Django 5.0.2 on 2025-01-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_category_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='productImage'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='productImage'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='productImage'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='productImage'),
        ),
    ]
