# Generated by Django 5.0.2 on 2025-01-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
