# Generated by Django 5.0.2 on 2025-02-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='discountedPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='orginalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
