# Generated by Django 5.0.2 on 2025-02-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_price_product_discountedprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountedPrice',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='orginalPrice',
            field=models.FloatField(blank=True, default=4, null=True),
        ),
    ]
